version: "2.1"
services:
  zakuro:
    image: zakuroai/agent
    container_name: zakuro_agent
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - UID=1000
      - GID=1000
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - $HOME/.config/zakuro/config:/config
      - $HOME/.config/zakuro/lib/modules:/lib/modules
      - $SRV:/srv
      - $FILESTORE:/FileStore
    ports:
      - 51820:51820/udp
      - 7077:7077/udp
      - 8080:8080/udp
      - 8890:8890/tcp
    restart: unless-stopped
