# matches bfd8deac from resnet18-bfd8deac.pth
HASH_REGEX_EXP: '-([a-f0-9]*)\.'

ZAKURO_HOME: '$HOME/.zakuro'
ZAKURO_HUB: 'http://hub.zakuro.ai/state_dict'
DEFAULT_CACHE_DIR: '$HOME/.cache'
XDG_CACHE_HOME: 'XDG_CACHE_HOME'
READ_DATA_CHUNK: 8192

host: "zfs:9000" #auto
username: minioadmin
password: minioadmin