"""Generate NOTICE from the resolved Python + Rust dependency tree.

Runs in CI after `uv sync` so the venv is populated. The output replaces the
top-level `NOTICE` file in-place; CI compares the regenerated file to the
checked-in one to detect drift (`task notice:check`).

Inputs the script reads:
  * the active Python env (via `pip-licenses --format=json --with-license-file
    --no-license-path`) for the wheel's runtime deps,
  * `cargo metadata --locked --format-version 1` for the Rust workspace deps.

The Rust path is best-effort: if `cargo` is not on PATH (Python-only CI lane),
the Rust section is skipped with a banner so the resulting NOTICE is still
deterministic against the inputs that were available.
"""

from __future__ import annotations

import json
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NOTICE_PATH = ROOT / "NOTICE"


def _run(cmd: list[str]) -> str:
    return subprocess.check_output(cmd, cwd=ROOT, text=True)


def collect_python() -> list[dict[str, str]]:
    raw = _run(["uv", "run", "pip-licenses", "--format=json", "--with-urls"])
    data = json.loads(raw)
    out = []
    for row in data:
        if row["Name"].lower() == "zakuro-ai":
            continue
        out.append(
            {
                "name": row["Name"],
                "version": row["Version"],
                "license": row["License"] or "UNKNOWN",
                "url": row.get("URL", "") or "",
            }
        )
    return sorted(out, key=lambda r: r["name"].lower())


def collect_rust() -> list[dict[str, str]] | None:
    try:
        raw = _run(["cargo", "metadata", "--locked", "--format-version", "1"])
    except (FileNotFoundError, subprocess.CalledProcessError):
        return None
    data = json.loads(raw)
    workspace_members = set(data.get("workspace_members", []))
    out = []
    for pkg in data.get("packages", []):
        pkg_id = pkg["id"]
        if pkg_id in workspace_members:
            continue
        out.append(
            {
                "name": pkg["name"],
                "version": pkg["version"],
                "license": pkg.get("license") or "UNKNOWN",
                "url": pkg.get("repository") or pkg.get("homepage") or "",
            }
        )
    return sorted(out, key=lambda r: r["name"].lower())


def _by_licence(rows: list[dict[str, str]]) -> dict[str, list[dict[str, str]]]:
    buckets: dict[str, list[dict[str, str]]] = defaultdict(list)
    for r in rows:
        buckets[r["license"]].append(r)
    return dict(sorted(buckets.items(), key=lambda kv: kv[0].lower()))


def render(py: list[dict[str, str]], rust: list[dict[str, str]] | None) -> str:
    lines: list[str] = []
    lines.append("Zakuro")
    lines.append("Copyright (c) Zakuro AI contributors.")
    lines.append("")
    lines.append(
        "Distributed under the BSD-3-Clause licence (see LICENSE). This NOTICE lists"
    )
    lines.append("third-party components bundled into, or required at runtime by, the published")
    lines.append("Zakuro wheels and container images.")
    lines.append("")
    lines.append("To refresh this file:")
    lines.append("")
    lines.append("    task notice:generate")
    lines.append("")
    lines.append("CI ensures this file matches the resolved dependency tree on every PR.")
    lines.append("")
    lines.append("=" * 78)
    lines.append("Python runtime dependencies")
    lines.append("=" * 78)
    lines.append("")
    for lic, rows in _by_licence(py).items():
        lines.append(f"--- {lic} ({len(rows)} package(s)) ---")
        for r in rows:
            url = f"  <{r['url']}>" if r["url"] else ""
            lines.append(f"  * {r['name']} {r['version']}{url}")
        lines.append("")

    lines.append("=" * 78)
    lines.append("Rust workspace dependencies")
    lines.append("=" * 78)
    lines.append("")
    if rust is None:
        lines.append("(cargo not available in this build environment — Rust section skipped;")
        lines.append("the canonical NOTICE is generated by the release workflow which always")
        lines.append("has cargo on PATH.)")
        lines.append("")
    else:
        for lic, rows in _by_licence(rust).items():
            lines.append(f"--- {lic} ({len(rows)} crate(s)) ---")
            for r in rows:
                url = f"  <{r['url']}>" if r["url"] else ""
                lines.append(f"  * {r['name']} {r['version']}{url}")
            lines.append("")

    lines.append("=" * 78)
    lines.append("Notes")
    lines.append("=" * 78)
    lines.append("")
    lines.append(
        "Where a third-party licence requires preservation of its own NOTICE file, that"
    )
    lines.append(
        "NOTICE is shipped alongside the package's wheel and is reproduced in the OCI"
    )
    lines.append("image at /usr/share/doc/<package>/NOTICE.")
    lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    py = collect_python()
    rust = collect_rust()
    NOTICE_PATH.write_text(render(py, rust), encoding="utf-8")
    print(f"Wrote {NOTICE_PATH.relative_to(ROOT)}: {len(py)} python deps, ", end="")
    print(f"{len(rust) if rust is not None else 'skipped'} rust crates.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
